<h2 style="text-align: center;">Dataset Cleaning and Preparation for EDA and ML Models</h2>

<h2 style="text-align: center;">Executive Summary</h2>

#### In the world of data science, I believe the principle of 'Mise en place' to be of utmost importance, similar to its essential role in culinary practices. Much like organizing ingredients before cooking, meticulously preparing a dataset—verifying its completeness, addressing missing values, validating data types, and ensuring correct formatting—lays the groundwork for seamless analysis and interpretation.

#### Within this project, I focus on cleaning and preparing on-time performance data of commercial flights into a usable dataset. The end result is a Pandas DataFrame that can serve for exploratory data analysis (EDA) or as a solid starting point for designing machine learning models.

#### The raw data is sourced from an online data base called “Airline On-Time Performance Data,” and can be found at the website for the Bureau of Transportation Statistics. According to the website, the database contains, “Monthly data reported by US certified air carriers that account for at least one percent of domestic scheduled passenger revenues--includes scheduled and actual arrival and departure times for flights.” This is the link to their aviation databases: https://www.transtats.bts.gov/databases.asp?Z1qr_VQ=E&Z1qr_Qr5p=N8vn6v10&f7owrp6_VQF=D

<br>

<h3 style="text-align: center;">DF Transformation</h3>

<div align="center">
            
|      | Rows       | Columns | DF Memory Usage|
|:-----------: | :--------: | :-----: | :--------------------: |
| Beginning    | 6,884,250  | 111     | 11.0 GB                |
| Ending       | 6,777,978  | 45      | 1.2+ GB                |

</div>

<br>

<h3 style="text-align: center;">Exported Dataset CSV</h3>

<div align="center">
            
|   Compression   | Size       |
|:-----------: | :--------: | 
| Zipped    | 206.6 MB | 
| Unzipped  | 1.48 GB | 

</div>

----
### **Notebook Objectives**:
* **Familiarize** myself with the dataset
    * Shapes
    * Distributions
    * Relationships
* **Identify** dataset quality issues
    * Missing values
    * Duplicate values
    * Dtypes
    * Formatting
* **Fix** the data quality issues
    * Drop empty columns
    * Remove redundant data
* **Format** DataFrame for EDA and ML <br><br>
* **Write** clean dataset to new file to be easily shared


##### **Note:** Diverted and Canceled flights will be omitted
----

## **Data Profiling**

### **Importing packages and data**

In [78]:
import pandas as pd
import numpy as np
import zipfile as zp
import os

pd.set_option('display.max_columns', 150)

In [79]:

df_zip_23_4 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_4.csv.zip')
df_zip_23_5 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_5.csv.zip')
df_zip_23_6 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_6.csv.zip')
df_zip_23_7 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_7.csv.zip')
df_zip_23_8 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_8.csv.zip')
df_zip_23_9 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_9.csv.zip')
df_zip_23_10 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_10.csv.zip')
df_zip_23_11 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_11.csv.zip')
df_zip_23_12 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_12.csv.zip')
df_zip_24_1 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv.zip')
df_zip_24_2 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_2.csv.zip')
df_zip_24_3 = zp.ZipFile('../Data_Science/Raw Data/On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_3.csv.zip')

In [80]:
df_23_4 = pd.read_csv(df_zip_23_4.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_4.csv'),low_memory=False)
df_23_5 = pd.read_csv(df_zip_23_5.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_5.csv'),low_memory=False)
df_23_6 = pd.read_csv(df_zip_23_6.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_6.csv'),low_memory=False)
df_23_7 = pd.read_csv(df_zip_23_7.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_7.csv'),low_memory=False)
df_23_8 = pd.read_csv(df_zip_23_8.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_8.csv'),low_memory=False)
df_23_9 = pd.read_csv(df_zip_23_9.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_9.csv'),low_memory=False)
df_23_10 = pd.read_csv(df_zip_23_10.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_10.csv'),low_memory=False)
df_23_11 = pd.read_csv(df_zip_23_11.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_11.csv'),low_memory=False)
df_23_12 = pd.read_csv(df_zip_23_12.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2023_12.csv'),low_memory=False)
df_24_1 = pd.read_csv(df_zip_24_1.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_1.csv'),low_memory=False)
df_24_2 = pd.read_csv(df_zip_24_2.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_2.csv'),low_memory=False)
df_24_3 = pd.read_csv(df_zip_24_3.open('On_Time_Reporting_Carrier_On_Time_Performance_(1987_present)_2024_3.csv'),low_memory=False)

In [81]:
### Making DF from which to work from

df = pd.concat([df_23_4, df_23_5, df_23_6, df_23_7, df_23_8, df_23_9, df_23_10, df_23_11, df_23_12, df_24_1, df_24_2, df_24_3])
df.reset_index(inplace=True)

### **Identifying initial shape and column names**

In [82]:
print('Original shape: ','\n\n',df.shape,'\n')

print('Original columns: ','\n\n', df.columns.values)

Original shape:

 (6884250, 111)

Original columns:

 ['index' 'Year' 'Quarter' 'Month' 'DayofMonth' 'DayOfWeek' 'FlightDate'
 'Reporting_Airline' 'DOT_ID_Reporting_Airline'
 'IATA_CODE_Reporting_Airline' 'Tail_Number'
 'Flight_Number_Reporting_Airline' 'OriginAirportID' 'OriginAirportSeqID'
 'OriginCityMarketID' 'Origin' 'OriginCityName' 'OriginState'
 'OriginStateFips' 'OriginStateName' 'OriginWac' 'DestAirportID'
 'DestAirportSeqID' 'DestCityMarketID' 'Dest' 'DestCityName' 'DestState'
 'DestStateFips' 'DestStateName' 'DestWac' 'CRSDepTime' 'DepTime'
 'DepDelay' 'DepDelayMinutes' 'DepDel15' 'DepartureDelayGroups'
 'DepTimeBlk' 'TaxiOut' 'WheelsOff' 'WheelsOn' 'TaxiIn' 'CRSArrTime'
 'ArrTime' 'ArrDelay' 'ArrDelayMinutes' 'ArrDel15' 'ArrivalDelayGroups'
 'ArrTimeBlk' 'Cancelled' 'CancellationCode' 'Diverted' 'CRSElapsedTime'
 'ActualElapsedTime' 'AirTime' 'Flights' 'Distance' 'DistanceGroup'
 'CarrierDelay' 'WeatherDelay' 'NASDelay' 'SecurityDelay'
 'LateAircraftDelay' 'FirstDepTime' 'TotalAddGTime' 'LongestAddGTime'
 'DivAirportLandings' 'DivReachedDest' 'DivActualElapsedTime'
 'DivArrDelay' 'DivDistance' 'Div1Airport' 'Div1AirportID'
 'Div1AirportSeqID' 'Div1WheelsOn' 'Div1TotalGTime' 'Div1LongestGTime'
 'Div1WheelsOff' 'Div1TailNum' 'Div2Airport' 'Div2AirportID'
 'Div2AirportSeqID' 'Div2WheelsOn' 'Div2TotalGTime' 'Div2LongestGTime'
 'Div2WheelsOff' 'Div2TailNum' 'Div3Airport' 'Div3AirportID'
 'Div3AirportSeqID' 'Div3WheelsOn' 'Div3TotalGTime' 'Div3LongestGTime'
 'Div3WheelsOff' 'Div3TailNum' 'Div4Airport' 'Div4AirportID'
 'Div4AirportSeqID' 'Div4WheelsOn' 'Div4TotalGTime' 'Div4LongestGTime'
 'Div4WheelsOff' 'Div4TailNum' 'Div5Airport' 'Div5AirportID'
 'Div5AirportSeqID' 'Div5WheelsOn' 'Div5TotalGTime' 'Div5LongestGTime'
 'Div5WheelsOff' 'Div5TailNum' 'Unnamed: 109']

### **Identifying null value count and dtypes**

In [83]:
df.info(verbose=True, show_counts=True, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6884250 entries, 0 to 6884249
Data columns (total 111 columns):
 #    Column                           Non-Null Count    Dtype
---   ------                           --------------    -----
 0    index                            6884250 non-null  int64
 1    Year                             6884250 non-null  int64
 2    Quarter                          6884250 non-null  int64
 3    Month                            6884250 non-null  int64
 4    DayofMonth                       6884250 non-null  int64
 5    DayOfWeek                        6884250 non-null  int64
 6    FlightDate                       6884250 non-null  object
 7    Reporting_Airline                6884250 non-null  object
 8    DOT_ID_Reporting_Airline         6884250 non-null  int64
 9    IATA_CODE_Reporting_Airline      6884250 non-null  object
 10   Tail_Number                      6864637 non-null  object
 11   Flight_Number_Reporting_Airline  6884250 non-null  int64
 12   OriginAirportID                  6884250 non-null  int64
 13   OriginAirportSeqID               6884250 non-null  int64
 14   OriginCityMarketID               6884250 non-null  int64
 15   Origin                           6884250 non-null  object
 16   OriginCityName                   6884250 non-null  object
 17   OriginState                      6884250 non-null  object
 18   OriginStateFips                  6884250 non-null  int64
 19   OriginStateName                  6884250 non-null  object
 20   OriginWac                        6884250 non-null  int64
 21   DestAirportID                    6884250 non-null  int64
 22   DestAirportSeqID                 6884250 non-null  int64
 23   DestCityMarketID                 6884250 non-null  int64
 24   Dest                             6884250 non-null  object
 25   DestCityName                     6884250 non-null  object
 26   DestState                        6884250 non-null  object
 27   DestStateFips                    6884250 non-null  int64
 28   DestStateName                    6884250 non-null  object
 29   DestWac                          6884250 non-null  int64
 30   CRSDepTime                       6884250 non-null  int64
 31   DepTime                          6798167 non-null  float64
 32   DepDelay                         6797991 non-null  float64
 33   DepDelayMinutes                  6797991 non-null  float64
 34   DepDel15                         6797991 non-null  float64
 35   DepartureDelayGroups             6797991 non-null  float64
 36   DepTimeBlk                       6884250 non-null  object
 37   TaxiOut                          6795139 non-null  float64
 38   WheelsOff                        6795139 non-null  float64
 39   WheelsOn                         6792868 non-null  float64
 40   TaxiIn                           6792868 non-null  float64
 41   CRSArrTime                       6884250 non-null  int64
 42   ArrTime                          6792871 non-null  float64
 43   ArrDelay                         6777978 non-null  float64
 44   ArrDelayMinutes                  6777978 non-null  float64
 45   ArrDel15                         6777978 non-null  float64
 46   ArrivalDelayGroups               6777978 non-null  float64
 47   ArrTimeBlk                       6884250 non-null  object
 48   Cancelled                        6884250 non-null  float64
 49   CancellationCode                 89734 non-null    object
 50   Diverted                         6884250 non-null  float64
 51   CRSElapsedTime                   6884249 non-null  float64
 52   ActualElapsedTime                6777978 non-null  float64
 53   AirTime                          6777978 non-null  float64
 54   Flights                          6884250 non-null  float64
 55   Distance                         6884250 non-null  float64
 56   DistanceGroup                    6884250 non-null  int64
 57   CarrierDelay                     1371450 non-null  float64
 58   WeatherDelay                     1371450 non-null  float64
 59   NASDelay                         1371450 non-null  float64
 60   SecurityDelay                    1371450 non-null  float64
 61   LateAircraftDelay                1371450 non-null  float64
 62   FirstDepTime                     45834 non-null    float64
 63   TotalAddGTime                    45832 non-null    float64
 64   LongestAddGTime                  45832 non-null    float64
 65   DivAirportLandings               6884247 non-null  float64
 66   DivReachedDest                   16537 non-null    float64
 67   DivActualElapsedTime             14892 non-null    float64
 68   DivArrDelay                      14893 non-null    float64
 69   DivDistance                      16537 non-null    float64
 70   Div1Airport                      17164 non-null    object
 71   Div1AirportID                    17164 non-null    float64
 72   Div1AirportSeqID                 17164 non-null    float64
 73   Div1WheelsOn                     17163 non-null    float64
 74   Div1TotalGTime                   17163 non-null    float64
 75   Div1LongestGTime                 17163 non-null    float64
 76   Div1WheelsOff                    14992 non-null    float64
 77   Div1TailNum                      14992 non-null    object
 78   Div2Airport                      194 non-null      object
 79   Div2AirportID                    195 non-null      float64
 80   Div2AirportSeqID                 195 non-null      float64
 81   Div2WheelsOn                     194 non-null      float64
 82   Div2TotalGTime                   194 non-null      float64
 83   Div2LongestGTime                 194 non-null      float64
 84   Div2WheelsOff                    99 non-null       float64
 85   Div2TailNum                      99 non-null       object
 86   Div3Airport                      3 non-null        object
 87   Div3AirportID                    3 non-null        float64
 88   Div3AirportSeqID                 3 non-null        float64
 89   Div3WheelsOn                     3 non-null        float64
 90   Div3TotalGTime                   3 non-null        float64
 91   Div3LongestGTime                 3 non-null        float64
 92   Div3WheelsOff                    2 non-null        float64
 93   Div3TailNum                      2 non-null        object
 94   Div4Airport                      0 non-null        float64
 95   Div4AirportID                    0 non-null        float64
 96   Div4AirportSeqID                 0 non-null        float64
 97   Div4WheelsOn                     0 non-null        float64
 98   Div4TotalGTime                   0 non-null        float64
 99   Div4LongestGTime                 0 non-null        float64
 100  Div4WheelsOff                    0 non-null        float64
 101  Div4TailNum                      0 non-null        float64
 102  Div5Airport                      0 non-null        float64
 103  Div5AirportID                    0 non-null        float64
 104  Div5AirportSeqID                 0 non-null        float64
 105  Div5WheelsOn                     0 non-null        float64
 106  Div5TotalGTime                   0 non-null        float64
 107  Div5LongestGTime                 0 non-null        float64
 108  Div5WheelsOff                    0 non-null        float64
 109  Div5TailNum                      0 non-null        float64
 110  Unnamed: 109                     0 non-null        float64
dtypes: float64(69), int64(21), object(21)
memory usage: 11.0 GB

## **Data Cleaning**

### **Removing the columns containing diverted flight details** (Since the majority of them contain null values)

In [84]:
df.drop(df.iloc[:,65:], inplace=True, axis=1)

### **Removing Extraneous Data**

##### From the documentation we learn that the Reporting_Airline is for "use across a range of years," and the the IATA_CODE_Reporting_Airline is not always unique, so for our purposes we will remove them.

In [85]:
df.drop(['Reporting_Airline', 'IATA_CODE_Reporting_Airline'], axis=1, inplace=True)

##### To decrease the size of our DataFrame for further analysis:
* We will limit geographic data to OriginAirportID, Orgin, OriginCityName, and OriginCityMarket (a unique identifier to consolidate airports serving the same city market). <br>We will also do the same for flight destination fields.
* Regarding departure and arrival performance, some data inherently captures other data so we will drop columns accordingly.
* We will remove columns about gate return information at origin airport, i.e. FirstDepTime, TotalAddGTime, and LongestAddGTime.

In [86]:
### Making a subset of column names to keep by commenting out those to be dropped

df = df[['Year', 'Quarter', 'Month', 'DayofMonth', 'DayOfWeek',
       'FlightDate', 'DOT_ID_Reporting_Airline', 'Tail_Number',
       'Flight_Number_Reporting_Airline', 'OriginAirportID',
       #'OriginAirportSeqID',
       'OriginCityMarketID', 'Origin','OriginCityName',
       #'OriginState', 'OriginStateFips','OriginStateName', 'OriginWac',
       'DestAirportID',
       #'DestAirportSeqID',
       'DestCityMarketID', 'Dest', 'DestCityName',
       #'DestState', 'DestStateFips', 'DestStateName', 'DestWac',
       'CRSDepTime', 'DepTime',
       'DepDelay', 'DepDelayMinutes', 'DepDel15',
       #'DepartureDelayGroups',
       'DepTimeBlk',
       #'TaxiOut', 'WheelsOff',
       #'WheelsOn', 'TaxiIn',
       'CRSArrTime', 'ArrTime',
       'ArrDelay','ArrDelayMinutes','ArrDel15',
       #'ArrivalDelayGroups',
       'ArrTimeBlk',
       'Cancelled', 'CancellationCode', 'Diverted',
       'CRSElapsedTime','ActualElapsedTime', 'AirTime', 'Flights', 'Distance',
       'DistanceGroup', 'CarrierDelay', 'WeatherDelay', 'NASDelay',
       'SecurityDelay', 'LateAircraftDelay',
       #'FirstDepTime','TotalAddGTime', 'LongestAddGTime', 'DivAirportLandings'
       ]].copy()

In [87]:
df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,DOT_ID_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginCityMarketID,Origin,OriginCityName,DestAirportID,DestCityMarketID,Dest,DestCityName,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepTimeBlk,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrTimeBlk,Cancelled,CancellationCode,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2023,2,4,26,3,2023-04-26,19977,N851UA,1788,11298,30194,DFW,"Dallas/Fort Worth, TX",11618,31703,EWR,"Newark, NJ",1926,1933.0,7.0,7.0,0.0,1900-1959,2359,12.0,13.0,13.0,0.0,2300-2359,0.0,NaN,0.0,213.0,219.0,162.0,1.0,1372.0,6,NaN,NaN,NaN,NaN,NaN
1,2023,2,4,26,3,2023-04-26,19977,N37530,1787,11292,30325,DEN,"Denver, CO",13871,33316,OMA,"Omaha, NE",2051,2130.0,39.0,39.0,1.0,2000-2059,2316,3.0,47.0,47.0,1.0,2300-2359,0.0,NaN,0.0,85.0,93.0,65.0,1.0,472.0,2,39.0,0.0,8.0,0.0,0.0
2,2023,2,4,26,3,2023-04-26,19977,N78509,1786,12892,32575,LAX,"Los Angeles, CA",11042,30647,CLE,"Cleveland, OH",2328,2319.0,-9.0,0.0,0.0,2300-2359,701,650.0,-11.0,0.0,0.0,0700-0759,0.0,NaN,0.0,273.0,271.0,249.0,1.0,2052.0,9,NaN,NaN,NaN,NaN,NaN
3,2023,2,4,26,3,2023-04-26,19977,N47280,1785,10721,30721,BOS,"Boston, MA",12264,30852,IAD,"Washington, DC",600,557.0,-3.0,0.0,0.0,0600-0659,735,724.0,-11.0,0.0,0.0,0700-0759,0.0,NaN,0.0,95.0,87.0,69.0,1.0,413.0,2,NaN,NaN,NaN,NaN,NaN
4,2023,2,4,26,3,2023-04-26,19977,N826UA,1784,14747,30559,SEA,"Seattle, WA",11292,30325,DEN,"Denver, CO",1116,1113.0,-3.0,0.0,0.0,1100-1159,1459,1453.0,-6.0,0.0,0.0,1400-1459,0.0,NaN,0.0,163.0,160.0,129.0,1.0,1024.0,5,NaN,NaN,NaN,NaN,NaN

In [88]:
df.info(verbose=True, show_counts=True, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6884250 entries, 0 to 6884249
Data columns (total 43 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   Year                             6884250 non-null  int64
 1   Quarter                          6884250 non-null  int64
 2   Month                            6884250 non-null  int64
 3   DayofMonth                       6884250 non-null  int64
 4   DayOfWeek                        6884250 non-null  int64
 5   FlightDate                       6884250 non-null  object
 6   DOT_ID_Reporting_Airline         6884250 non-null  int64
 7   Tail_Number                      6864637 non-null  object
 8   Flight_Number_Reporting_Airline  6884250 non-null  int64
 9   OriginAirportID                  6884250 non-null  int64
 10  OriginCityMarketID               6884250 non-null  int64
 11  Origin                           6884250 non-null  object
 12  OriginCityName                   6884250 non-null  object
 13  DestAirportID                    6884250 non-null  int64
 14  DestCityMarketID                 6884250 non-null  int64
 15  Dest                             6884250 non-null  object
 16  DestCityName                     6884250 non-null  object
 17  CRSDepTime                       6884250 non-null  int64
 18  DepTime                          6798167 non-null  float64
 19  DepDelay                         6797991 non-null  float64
 20  DepDelayMinutes                  6797991 non-null  float64
 21  DepDel15                         6797991 non-null  float64
 22  DepTimeBlk                       6884250 non-null  object
 23  CRSArrTime                       6884250 non-null  int64
 24  ArrTime                          6792871 non-null  float64
 25  ArrDelay                         6777978 non-null  float64
 26  ArrDelayMinutes                  6777978 non-null  float64
 27  ArrDel15                         6777978 non-null  float64
 28  ArrTimeBlk                       6884250 non-null  object
 29  Cancelled                        6884250 non-null  float64
 30  CancellationCode                 89734 non-null    object
 31  Diverted                         6884250 non-null  float64
 32  CRSElapsedTime                   6884249 non-null  float64
 33  ActualElapsedTime                6777978 non-null  float64
 34  AirTime                          6777978 non-null  float64
 35  Flights                          6884250 non-null  float64
 36  Distance                         6884250 non-null  float64
 37  DistanceGroup                    6884250 non-null  int64
 38  CarrierDelay                     1371450 non-null  float64
 39  WeatherDelay                     1371450 non-null  float64
 40  NASDelay                         1371450 non-null  float64
 41  SecurityDelay                    1371450 non-null  float64
 42  LateAircraftDelay                1371450 non-null  float64
dtypes: float64(20), int64(14), object(9)
memory usage: 4.9 GB

### **Handling Missing Data**

##### **Tail_Number**

In [89]:
### Creating a list of indices where the value for Tail_Number is null

tail_number_na_rows = df[df['Tail_Number'].isna()].index

In [90]:
### Dropping rows contained in the list

df.drop(tail_number_na_rows, inplace = True)

##### **DepDelay, DepDelayMinutes, DepDel15**

In [91]:
### Creating a list of indices where the value for DepDelay is null

depdelay_na_rows = df[df['DepDelay'].isna()].index

In [92]:
### Dropping rows contained in the list

df.drop(depdelay_na_rows, inplace = True)

##### **ArrTime, ArrDelay, ArrDel15**

In [93]:
### Creating a list of indices where the value for ArrDelay is null

arrdelay_na_rows = df[df['ArrDelay'].isna()].index

In [94]:
### Dropping rows contained in the list

df.drop(arrdelay_na_rows, inplace = True)

In [95]:
### Viewing results to see if removing DepDelay and ArrDelay resolved the
### DepDelayMinutes, DepDel15, ArrDelay, and ArrDel15 columns as well

df.info(verbose=True, show_counts=True, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 6777978 entries, 0 to 6884249
Data columns (total 43 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   Year                             6777978 non-null  int64
 1   Quarter                          6777978 non-null  int64
 2   Month                            6777978 non-null  int64
 3   DayofMonth                       6777978 non-null  int64
 4   DayOfWeek                        6777978 non-null  int64
 5   FlightDate                       6777978 non-null  object
 6   DOT_ID_Reporting_Airline         6777978 non-null  int64
 7   Tail_Number                      6777978 non-null  object
 8   Flight_Number_Reporting_Airline  6777978 non-null  int64
 9   OriginAirportID                  6777978 non-null  int64
 10  OriginCityMarketID               6777978 non-null  int64
 11  Origin                           6777978 non-null  object
 12  OriginCityName                   6777978 non-null  object
 13  DestAirportID                    6777978 non-null  int64
 14  DestCityMarketID                 6777978 non-null  int64
 15  Dest                             6777978 non-null  object
 16  DestCityName                     6777978 non-null  object
 17  CRSDepTime                       6777978 non-null  int64
 18  DepTime                          6777978 non-null  float64
 19  DepDelay                         6777978 non-null  float64
 20  DepDelayMinutes                  6777978 non-null  float64
 21  DepDel15                         6777978 non-null  float64
 22  DepTimeBlk                       6777978 non-null  object
 23  CRSArrTime                       6777978 non-null  int64
 24  ArrTime                          6777978 non-null  float64
 25  ArrDelay                         6777978 non-null  float64
 26  ArrDelayMinutes                  6777978 non-null  float64
 27  ArrDel15                         6777978 non-null  float64
 28  ArrTimeBlk                       6777978 non-null  object
 29  Cancelled                        6777978 non-null  float64
 30  CancellationCode                 0 non-null        object
 31  Diverted                         6777978 non-null  float64
 32  CRSElapsedTime                   6777978 non-null  float64
 33  ActualElapsedTime                6777978 non-null  float64
 34  AirTime                          6777978 non-null  float64
 35  Flights                          6777978 non-null  float64
 36  Distance                         6777978 non-null  float64
 37  DistanceGroup                    6777978 non-null  int64
 38  CarrierDelay                     1371450 non-null  float64
 39  WeatherDelay                     1371450 non-null  float64
 40  NASDelay                         1371450 non-null  float64
 41  SecurityDelay                    1371450 non-null  float64
 42  LateAircraftDelay                1371450 non-null  float64
dtypes: float64(20), int64(14), object(9)
memory usage: 4.9 GB

##### **CancellationCode**

In [96]:
### Deleting whole column since all the values are null
df.drop(['CancellationCode'], axis=1, inplace=True)

### **Changing Dtypes** (Optimizing DataFrame Size)

In [97]:
### Dtypes BEFORE
df.info(verbose=True, show_counts=True, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 6777978 entries, 0 to 6884249
Data columns (total 42 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   Year                             6777978 non-null  int64
 1   Quarter                          6777978 non-null  int64
 2   Month                            6777978 non-null  int64
 3   DayofMonth                       6777978 non-null  int64
 4   DayOfWeek                        6777978 non-null  int64
 5   FlightDate                       6777978 non-null  object
 6   DOT_ID_Reporting_Airline         6777978 non-null  int64
 7   Tail_Number                      6777978 non-null  object
 8   Flight_Number_Reporting_Airline  6777978 non-null  int64
 9   OriginAirportID                  6777978 non-null  int64
 10  OriginCityMarketID               6777978 non-null  int64
 11  Origin                           6777978 non-null  object
 12  OriginCityName                   6777978 non-null  object
 13  DestAirportID                    6777978 non-null  int64
 14  DestCityMarketID                 6777978 non-null  int64
 15  Dest                             6777978 non-null  object
 16  DestCityName                     6777978 non-null  object
 17  CRSDepTime                       6777978 non-null  int64
 18  DepTime                          6777978 non-null  float64
 19  DepDelay                         6777978 non-null  float64
 20  DepDelayMinutes                  6777978 non-null  float64
 21  DepDel15                         6777978 non-null  float64
 22  DepTimeBlk                       6777978 non-null  object
 23  CRSArrTime                       6777978 non-null  int64
 24  ArrTime                          6777978 non-null  float64
 25  ArrDelay                         6777978 non-null  float64
 26  ArrDelayMinutes                  6777978 non-null  float64
 27  ArrDel15                         6777978 non-null  float64
 28  ArrTimeBlk                       6777978 non-null  object
 29  Cancelled                        6777978 non-null  float64
 30  Diverted                         6777978 non-null  float64
 31  CRSElapsedTime                   6777978 non-null  float64
 32  ActualElapsedTime                6777978 non-null  float64
 33  AirTime                          6777978 non-null  float64
 34  Flights                          6777978 non-null  float64
 35  Distance                         6777978 non-null  float64
 36  DistanceGroup                    6777978 non-null  int64
 37  CarrierDelay                     1371450 non-null  float64
 38  WeatherDelay                     1371450 non-null  float64
 39  NASDelay                         1371450 non-null  float64
 40  SecurityDelay                    1371450 non-null  float64
 41  LateAircraftDelay                1371450 non-null  float64
dtypes: float64(20), int64(14), object(8)
memory usage: 4.7 GB

In [98]:
### Identify the maximum values to determine the appropriate integer data type for the columns

df.describe()

,Year,Quarter,Month,DayofMonth,DayOfWeek,DOT_ID_Reporting_Airline,Flight_Number_Reporting_Airline,OriginAirportID,OriginCityMarketID,DestAirportID,DestCityMarketID,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,Cancelled,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
count,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6.777978e+06,6777978.0,6777978.0,6.777978e+06,6.777978e+06,6.777978e+06,6777978.0,6.777978e+06,6.777978e+06,1.371450e+06,1.371450e+06,1.371450e+06,1.371450e+06,1.371450e+06
mean,2.023240e+03,2.525636e+00,6.579765e+00,1.578010e+01,3.993577e+00,1.993903e+04,2.326942e+03,1.265096e+04,3.173691e+04,1.265146e+04,3.173762e+04,1.329214e+03,1.332679e+03,1.213807e+01,1.529571e+01,2.025111e-01,1.487477e+03,1.458442e+03,6.331910e+00,1.518102e+01,2.023393e-01,0.0,0.0,1.463600e+02,1.405534e+02,1.150121e+02,1.0,8.350128e+02,3.812710e+00,2.500295e+01,3.889372e+00,1.266256e+01,1.541595e-01,2.828230e+01
std,4.270236e-01,1.112769e+00,3.417310e+00,8.798410e+00,2.002280e+00,3.727813e+02,1.572670e+03,1.531122e+03,1.315375e+03,1.531433e+03,1.315764e+03,4.956277e+02,5.115607e+02,5.550007e+01,5.449913e+01,4.018711e-01,5.241219e+02,5.489676e+02,5.759446e+01,5.431121e+01,4.017438e-01,0.0,0.0,7.295989e+01,7.264227e+01,7.051693e+01,0.0,5.979042e+02,2.345291e+00,7.772250e+01,3.263982e+01,3.161361e+01,3.478900e+00,6.377245e+01
min,2.023000e+03,1.000000e+00,1.000000e+00,1.000000e+00,1.000000e+00,1.939300e+04,1.000000e+00,1.013500e+04,3.007000e+04,1.013500e+04,3.007000e+04,1.000000e+00,1.000000e+00,-9.900000e+01,0.000000e+00,0.000000e+00,1.000000e+00,1.000000e+00,-1.190000e+02,0.000000e+00,0.000000e+00,0.0,0.0,1.000000e+00,1.500000e+01,6.000000e+00,1.0,2.100000e+01,1.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
25%,2.023000e+03,2.000000e+00,4.000000e+00,8.000000e+00,2.000000e+00,1.979000e+04,1.064000e+03,1.129200e+04,3.064700e+04,1.129200e+04,3.064700e+04,9.060000e+02,9.080000e+02,-6.000000e+00,0.000000e+00,0.000000e+00,1.100000e+03,1.041000e+03,-1.500000e+01,0.000000e+00,0.000000e+00,0.0,0.0,9.300000e+01,8.700000e+01,6.300000e+01,1.0,3.990000e+02,2.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00
50%,2.023000e+03,3.000000e+00,7.000000e+00,1.600000e+01,4.000000e+00,1.980500e+04,2.077000e+03,1.288900e+04,3.145300e+04,1.288900e+04,3.145300e+04,1.320000e+03,1.325000e+03,-2.000000e+00,0.000000e+00,0.000000e+00,1.515000e+03,1.500000e+03,-6.000000e+00,0.000000e+00,0.000000e+00,0.0,0.0,1.300000e+02,1.240000e+02,9.800000e+01,1.0,6.800000e+02,3.000000e+00,4.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,3.000000e+00
75%,2.023000e+03,4.000000e+00,1.000000e+01,2.300000e+01,6.000000e+00,2.036300e+04,3.399000e+03,1.402700e+04,3.246700e+04,1.402700e+04,3.246700e+04,1.740000e+03,1.749000e+03,9.000000e+00,9.000000e+00,0.000000e+00,1.925000e+03,1.919000e+03,9.000000e+00,9.000000e+00,0.000000e+00,0.0,0.0,1.770000e+02,1.720000e+02,1.450000e+02,1.0,1.069000e+03,5.000000e+00,2.200000e+01,0.000000e+00,1.600000e+01,0.000000e+00,3.200000e+01
max,2.024000e+03,4.000000e+00,1.200000e+01,3.100000e+01,7.000000e+00,2.045200e+04,8.819000e+03,1.686900e+04,3.599100e+04,1.686900e+04,3.599100e+04,2.400000e+03,2.400000e+03,3.786000e+03,3.786000e+03,1.000000e+00,2.400000e+03,2.400000e+03,3.795000e+03,3.795000e+03,1.000000e+00,0.0,0.0,1.162000e+03,7.950000e+02,7.230000e+02,1.0,5.095000e+03,1.100000e+01,3.786000e+03,1.860000e+03,1.708000e+03,1.183000e+03,3.581000e+03

In [99]:
### dtype = datetime64

df[['FlightDate']] = df[['FlightDate']].astype('datetime64[ns]')

In [100]:
### dtype = int8

df[['Quarter','Month','DayofMonth','DayOfWeek','DepDel15','ArrDel15',
    'Cancelled','Diverted','Flights','DistanceGroup']]=\
    df[['Quarter','Month','DayofMonth','DayOfWeek','DepDel15','ArrDel15',
        'Cancelled','Diverted','Flights','DistanceGroup']].astype(np.int8)

In [101]:
### dtype = int16

df[['Year','DOT_ID_Reporting_Airline','Flight_Number_Reporting_Airline',
    'OriginAirportID','DestAirportID','CRSDepTime','DepTime','DepDelay',
    'DepDelayMinutes','CRSArrTime','ArrTime','ArrDelay','ArrDelayMinutes',
    'CRSElapsedTime','ActualElapsedTime','AirTime','Distance']]=\
    df[['Year','DOT_ID_Reporting_Airline','Flight_Number_Reporting_Airline',
    'OriginAirportID','DestAirportID','CRSDepTime','DepTime','DepDelay',
    'DepDelayMinutes','CRSArrTime','ArrTime','ArrDelay','ArrDelayMinutes',
    'CRSElapsedTime','ActualElapsedTime','AirTime','Distance']].astype(np.int16)

In [102]:
### dtype = int32

df[['OriginCityMarketID','DestCityMarketID']]=\
    df[['OriginCityMarketID','DestCityMarketID']].astype(np.int32)

In [103]:
### Dtypes AFTER
df.info(verbose=True, show_counts=True, memory_usage='deep')

<class 'pandas.core.frame.DataFrame'>
Index: 6777978 entries, 0 to 6884249
Data columns (total 42 columns):
 #   Column                           Non-Null Count    Dtype
---  ------                           --------------    -----
 0   Year                             6777978 non-null  int16
 1   Quarter                          6777978 non-null  int8
 2   Month                            6777978 non-null  int8
 3   DayofMonth                       6777978 non-null  int8
 4   DayOfWeek                        6777978 non-null  int8
 5   FlightDate                       6777978 non-null  datetime64[ns]
 6   DOT_ID_Reporting_Airline         6777978 non-null  int16
 7   Tail_Number                      6777978 non-null  object
 8   Flight_Number_Reporting_Airline  6777978 non-null  int16
 9   OriginAirportID                  6777978 non-null  int16
 10  OriginCityMarketID               6777978 non-null  int32
 11  Origin                           6777978 non-null  object
 12  OriginCityName                   6777978 non-null  object
 13  DestAirportID                    6777978 non-null  int16
 14  DestCityMarketID                 6777978 non-null  int32
 15  Dest                             6777978 non-null  object
 16  DestCityName                     6777978 non-null  object
 17  CRSDepTime                       6777978 non-null  int16
 18  DepTime                          6777978 non-null  int16
 19  DepDelay                         6777978 non-null  int16
 20  DepDelayMinutes                  6777978 non-null  int16
 21  DepDel15                         6777978 non-null  int8
 22  DepTimeBlk                       6777978 non-null  object
 23  CRSArrTime                       6777978 non-null  int16
 24  ArrTime                          6777978 non-null  int16
 25  ArrDelay                         6777978 non-null  int16
 26  ArrDelayMinutes                  6777978 non-null  int16
 27  ArrDel15                         6777978 non-null  int8
 28  ArrTimeBlk                       6777978 non-null  object
 29  Cancelled                        6777978 non-null  int8
 30  Diverted                         6777978 non-null  int8
 31  CRSElapsedTime                   6777978 non-null  int16
 32  ActualElapsedTime                6777978 non-null  int16
 33  AirTime                          6777978 non-null  int16
 34  Flights                          6777978 non-null  int8
 35  Distance                         6777978 non-null  int16
 36  DistanceGroup                    6777978 non-null  int8
 37  CarrierDelay                     1371450 non-null  float64
 38  WeatherDelay                     1371450 non-null  float64
 39  NASDelay                         1371450 non-null  float64
 40  SecurityDelay                    1371450 non-null  float64
 41  LateAircraftDelay                1371450 non-null  float64
dtypes: datetime64[ns](1), float64(5), int16(17), int32(2), int8(10), object(7)
memory usage: 3.2 GB

In [104]:
### Verifying dtype changes

df.head()

,Year,Quarter,Month,DayofMonth,DayOfWeek,FlightDate,DOT_ID_Reporting_Airline,Tail_Number,Flight_Number_Reporting_Airline,OriginAirportID,OriginCityMarketID,Origin,OriginCityName,DestAirportID,DestCityMarketID,Dest,DestCityName,CRSDepTime,DepTime,DepDelay,DepDelayMinutes,DepDel15,DepTimeBlk,CRSArrTime,ArrTime,ArrDelay,ArrDelayMinutes,ArrDel15,ArrTimeBlk,Cancelled,Diverted,CRSElapsedTime,ActualElapsedTime,AirTime,Flights,Distance,DistanceGroup,CarrierDelay,WeatherDelay,NASDelay,SecurityDelay,LateAircraftDelay
0,2023,2,4,26,3,2023-04-26,19977,N851UA,1788,11298,30194,DFW,"Dallas/Fort Worth, TX",11618,31703,EWR,"Newark, NJ",1926,1933,7,7,0,1900-1959,2359,12,13,13,0,2300-2359,0,0,213,219,162,1,1372,6,NaN,NaN,NaN,NaN,NaN
1,2023,2,4,26,3,2023-04-26,19977,N37530,1787,11292,30325,DEN,"Denver, CO",13871,33316,OMA,"Omaha, NE",2051,2130,39,39,1,2000-2059,2316,3,47,47,1,2300-2359,0,0,85,93,65,1,472,2,39.0,0.0,8.0,0.0,0.0
2,2023,2,4,26,3,2023-04-26,19977,N78509,1786,12892,32575,LAX,"Los Angeles, CA",11042,30647,CLE,"Cleveland, OH",2328,2319,-9,0,0,2300-2359,701,650,-11,0,0,0700-0759,0,0,273,271,249,1,2052,9,NaN,NaN,NaN,NaN,NaN
3,2023,2,4,26,3,2023-04-26,19977,N47280,1785,10721,30721,BOS,"Boston, MA",12264,30852,IAD,"Washington, DC",600,557,-3,0,0,0600-0659,735,724,-11,0,0,0700-0759,0,0,95,87,69,1,413,2,NaN,NaN,NaN,NaN,NaN
4,2023,2,4,26,3,2023-04-26,19977,N826UA,1784,14747,30559,SEA,"Seattle, WA",11292,30325,DEN,"Denver, CO",1116,1113,-3,0,0,1100-1159,1459,1453,-6,0,0,1400-1459,0,0,163,160,129,1,1024,5,NaN,NaN,NaN,NaN,NaN

## **Column Formatting and Preliminary Data Mining and Feature Engineering**

### **Renaming Column Names**

##### Referencing the source data description, I change the column names to be more intuitive and uniform

In [105]:
df.rename(columns={"DayofMonth": "Month_Day",
                   "DayOfWeek": "Week_Day",
                   "FlightDate": "Flight_Date",
                   "DOT_ID_Reporting_Airline": "Airline_DOT_ID",
                   "Flight_Number_Reporting_Airline": "Flight_Number",
                   "OriginAirportID": "Origin_Airport_ID",
                   "OriginCityMarketID": "Origin_City_Market_ID",
                   "Origin": "Origin_IATA_Code",
                   "OriginCityName": "Origin_City_State",
                   "DestAirportID": "Destination_Airport_ID",
                   "DestCityMarketID": "Destination_City_Market_ID",
                   "Dest": "Destination_IATA_Code",
                   "DestCityName": "Destination_City_State",
                   "CRSDepTime": "Scheduled_Departure_Time",
                   "DepTime": "Actual_Dep_Time",
                   "DepDelay": "Dep_Time_Offset",
                   "DepDelayMinutes": "Dep_Delay_Minutes",
                   "DepDel15": "Dep_Delay_At_Least_15_Minutes",
                   "DepTimeBlk": "Dep_Time_Block",
                   "CRSArrTime": "Scheduled_Arrival_Time",
                   "ArrTime": "Actual_Arr_Time",
                   "ArrDelay": "Arr_Time_Offset",
                   "ArrDelayMinutes": "Arr_Delay_Minutes",
                   "ArrDel15": "Arr_Delay_At_Least_15_Minutes",
                   "ArrTimeBlk": "Arr_Time_Block",
                   "Cancelled": "Flight_Cancelled",
                   "CancellationCode": "Cancellation_Code",
                   "Diverted": "Flight_Diverted",
                   "CRSElapsedTime": "Scheduled_Gate_to_Gate_Time",
                   "ActualElapsedTime": "Actual_Gate_to_Gate_Time",
                   "AirTime": "Time_Airborne",
                   "Flights": "Number_of_Flights",
                   "Distance": "Distance_Miles",
                   "DistanceGroup": "Distance_Group",
                   "CarrierDelay": "Carrier_Delay",
                   "WeatherDelay": "Weather_Delay",
                   "NASDelay": "National_Aviation_System_Delay",
                   "SecurityDelay": "Security_Delay",
                   "LateAircraftDelay": "Late_Aircraft_Delay",
                   }, inplace = True)

In [106]:
df.head()

,Year,Quarter,Month,Month_Day,Week_Day,Flight_Date,Airline_DOT_ID,Tail_Number,Flight_Number,Origin_Airport_ID,Origin_City_Market_ID,Origin_IATA_Code,Origin_City_State,Destination_Airport_ID,Destination_City_Market_ID,Destination_IATA_Code,Destination_City_State,Scheduled_Departure_Time,Actual_Dep_Time,Dep_Time_Offset,Dep_Delay_Minutes,Dep_Delay_At_Least_15_Minutes,Dep_Time_Block,Scheduled_Arrival_Time,Actual_Arr_Time,Arr_Time_Offset,Arr_Delay_Minutes,Arr_Delay_At_Least_15_Minutes,Arr_Time_Block,Flight_Cancelled,Flight_Diverted,Scheduled_Gate_to_Gate_Time,Actual_Gate_to_Gate_Time,Time_Airborne,Number_of_Flights,Distance_Miles,Distance_Group,Carrier_Delay,Weather_Delay,National_Aviation_System_Delay,Security_Delay,Late_Aircraft_Delay
0,2023,2,4,26,3,2023-04-26,19977,N851UA,1788,11298,30194,DFW,"Dallas/Fort Worth, TX",11618,31703,EWR,"Newark, NJ",1926,1933,7,7,0,1900-1959,2359,12,13,13,0,2300-2359,0,0,213,219,162,1,1372,6,NaN,NaN,NaN,NaN,NaN
1,2023,2,4,26,3,2023-04-26,19977,N37530,1787,11292,30325,DEN,"Denver, CO",13871,33316,OMA,"Omaha, NE",2051,2130,39,39,1,2000-2059,2316,3,47,47,1,2300-2359,0,0,85,93,65,1,472,2,39.0,0.0,8.0,0.0,0.0
2,2023,2,4,26,3,2023-04-26,19977,N78509,1786,12892,32575,LAX,"Los Angeles, CA",11042,30647,CLE,"Cleveland, OH",2328,2319,-9,0,0,2300-2359,701,650,-11,0,0,0700-0759,0,0,273,271,249,1,2052,9,NaN,NaN,NaN,NaN,NaN
3,2023,2,4,26,3,2023-04-26,19977,N47280,1785,10721,30721,BOS,"Boston, MA",12264,30852,IAD,"Washington, DC",600,557,-3,0,0,0600-0659,735,724,-11,0,0,0700-0759,0,0,95,87,69,1,413,2,NaN,NaN,NaN,NaN,NaN
4,2023,2,4,26,3,2023-04-26,19977,N826UA,1784,14747,30559,SEA,"Seattle, WA",11292,30325,DEN,"Denver, CO",1116,1113,-3,0,0,1100-1159,1459,1453,-6,0,0,1400-1459,0,0,163,160,129,1,1024,5,NaN,NaN,NaN,NaN,NaN

### **Adding a Column with Carrier Names**

In [108]:
### Importing and creating a DF from csv containing carrier name and DOT ID

carrier_df = pd.read_csv('../Data_Science/Supplemental_Data/AIRLINE_ID_lookup_table.csv')

In [109]:
carrier_df.head()

    Code                      Description
0  19031   Mackey International Inc.: MAC
1  19032  Munz Northern Airlines Inc.: XY
2  19033       Cochise Airlines Inc.: COC
3  19034   Golden Gate Airlines Inc.: GSA
4  19035               Aeromech Inc.: RZZ

In [110]:
### Renaming "Description" column to "Carrier_Name"

carrier_df.rename(columns={"Description": "Carrier_Name"}, inplace = True)

In [111]:
### Removing IATA Airline Marketing Code from Carrier_Name column

carrier_df['Carrier_Name'] = carrier_df['Carrier_Name'].map(lambda x:x.split(':')[0])

In [112]:
carrier_df.head()

    Code                 Carrier_Name
0  19031    Mackey International Inc.
1  19032  Munz Northern Airlines Inc.
2  19033        Cochise Airlines Inc.
3  19034    Golden Gate Airlines Inc.
4  19035                Aeromech Inc.

In [113]:
### Adding Carrier_Name Column to main DF

df = df.join(carrier_df.set_index('Code'), on='Airline_DOT_ID')

In [114]:
### Moving the Carrier_Name to position 0

carrier_col = df.pop('Carrier_Name')
df.insert(0, 'Carrier_Name', carrier_col)
df.head()

,Carrier_Name,Year,Quarter,Month,Month_Day,Week_Day,Flight_Date,Airline_DOT_ID,Tail_Number,Flight_Number,Origin_Airport_ID,Origin_City_Market_ID,Origin_IATA_Code,Origin_City_State,Destination_Airport_ID,Destination_City_Market_ID,Destination_IATA_Code,Destination_City_State,Scheduled_Departure_Time,Actual_Dep_Time,Dep_Time_Offset,Dep_Delay_Minutes,Dep_Delay_At_Least_15_Minutes,Dep_Time_Block,Scheduled_Arrival_Time,Actual_Arr_Time,Arr_Time_Offset,Arr_Delay_Minutes,Arr_Delay_At_Least_15_Minutes,Arr_Time_Block,Flight_Cancelled,Flight_Diverted,Scheduled_Gate_to_Gate_Time,Actual_Gate_to_Gate_Time,Time_Airborne,Number_of_Flights,Distance_Miles,Distance_Group,Carrier_Delay,Weather_Delay,National_Aviation_System_Delay,Security_Delay,Late_Aircraft_Delay
0,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N851UA,1788,11298,30194,DFW,"Dallas/Fort Worth, TX",11618,31703,EWR,"Newark, NJ",1926,1933,7,7,0,1900-1959,2359,12,13,13,0,2300-2359,0,0,213,219,162,1,1372,6,NaN,NaN,NaN,NaN,NaN
1,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N37530,1787,11292,30325,DEN,"Denver, CO",13871,33316,OMA,"Omaha, NE",2051,2130,39,39,1,2000-2059,2316,3,47,47,1,2300-2359,0,0,85,93,65,1,472,2,39.0,0.0,8.0,0.0,0.0
2,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N78509,1786,12892,32575,LAX,"Los Angeles, CA",11042,30647,CLE,"Cleveland, OH",2328,2319,-9,0,0,2300-2359,701,650,-11,0,0,0700-0759,0,0,273,271,249,1,2052,9,NaN,NaN,NaN,NaN,NaN
3,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N47280,1785,10721,30721,BOS,"Boston, MA",12264,30852,IAD,"Washington, DC",600,557,-3,0,0,0600-0659,735,724,-11,0,0,0700-0759,0,0,95,87,69,1,413,2,NaN,NaN,NaN,NaN,NaN
4,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N826UA,1784,14747,30559,SEA,"Seattle, WA",11292,30325,DEN,"Denver, CO",1116,1113,-3,0,0,1100-1159,1459,1453,-6,0,0,1400-1459,0,0,163,160,129,1,1024,5,NaN,NaN,NaN,NaN,NaN

### **Grouping, Encoding Time Blocks, and Adding a Column with Time Block Group Names**

In [115]:
### Creating time block groups
early_morning = ['0001-0559', '0600-0659', '0700-0759']
morning = ['0800-0859', '0900-0959','1000-1059', '1100-1159']
early_afternoon = ['1200-1259', '1300-1359', '1400-1459']
afternoon = ['1500-1559', '1600-1659', '1700-1759']
evening = ['1800-1859', '1900-1959', '2000-2059']
night = ['2100-2159', '2200-2259', '2300-2359']

#### **Dep_Time_Block**

In [116]:
### Iterating over time block values in each row of the DF and simultaneously grouping and encoding them

time_blk = []
for blk in df['Dep_Time_Block']:
    if blk in early_morning:
      time_blk.append(0)
    elif blk in morning:
      time_blk.append(1)
    elif blk in early_afternoon:
      time_blk.append(2)
    elif blk in afternoon:
      time_blk.append(3)
    elif blk in evening:
      time_blk.append(4)
    else:
      time_blk.append(5)

In [117]:
### Converting the list into an array

time_blk = np.array(time_blk)

In [118]:
### Inserting array into DF

df.insert(loc = 18, column = 'Encoded_Dep_Time_Block', value = time_blk)

In [119]:
### Creating a list of departure time block groupings

time_blk_name = []
for blk in df['Encoded_Dep_Time_Block']:
    if blk == 0:
      time_blk_name.append('Early Morning')
    elif blk == 1:
      time_blk_name.append('Morning')
    elif blk == 2:
      time_blk_name.append('Early Afternoon')
    elif blk == 3:
      time_blk_name.append('Afternoon')
    elif blk == 4:
      time_blk_name.append('Evening')
    else:
      time_blk_name.append('Night')

In [120]:
### Inserting new "Dep_Time_Block_Group" column into DF

time_blk_name = np.array(time_blk_name)
df.insert(loc = 18, column = 'Dep_Time_Block_Group', value = time_blk_name)

In [121]:
df.head()

,Carrier_Name,Year,Quarter,Month,Month_Day,Week_Day,Flight_Date,Airline_DOT_ID,Tail_Number,Flight_Number,Origin_Airport_ID,Origin_City_Market_ID,Origin_IATA_Code,Origin_City_State,Destination_Airport_ID,Destination_City_Market_ID,Destination_IATA_Code,Destination_City_State,Dep_Time_Block_Group,Encoded_Dep_Time_Block,Scheduled_Departure_Time,Actual_Dep_Time,Dep_Time_Offset,Dep_Delay_Minutes,Dep_Delay_At_Least_15_Minutes,Dep_Time_Block,Scheduled_Arrival_Time,Actual_Arr_Time,Arr_Time_Offset,Arr_Delay_Minutes,Arr_Delay_At_Least_15_Minutes,Arr_Time_Block,Flight_Cancelled,Flight_Diverted,Scheduled_Gate_to_Gate_Time,Actual_Gate_to_Gate_Time,Time_Airborne,Number_of_Flights,Distance_Miles,Distance_Group,Carrier_Delay,Weather_Delay,National_Aviation_System_Delay,Security_Delay,Late_Aircraft_Delay
0,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N851UA,1788,11298,30194,DFW,"Dallas/Fort Worth, TX",11618,31703,EWR,"Newark, NJ",Evening,4,1926,1933,7,7,0,1900-1959,2359,12,13,13,0,2300-2359,0,0,213,219,162,1,1372,6,NaN,NaN,NaN,NaN,NaN
1,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N37530,1787,11292,30325,DEN,"Denver, CO",13871,33316,OMA,"Omaha, NE",Evening,4,2051,2130,39,39,1,2000-2059,2316,3,47,47,1,2300-2359,0,0,85,93,65,1,472,2,39.0,0.0,8.0,0.0,0.0
2,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N78509,1786,12892,32575,LAX,"Los Angeles, CA",11042,30647,CLE,"Cleveland, OH",Night,5,2328,2319,-9,0,0,2300-2359,701,650,-11,0,0,0700-0759,0,0,273,271,249,1,2052,9,NaN,NaN,NaN,NaN,NaN
3,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N47280,1785,10721,30721,BOS,"Boston, MA",12264,30852,IAD,"Washington, DC",Early Morning,0,600,557,-3,0,0,0600-0659,735,724,-11,0,0,0700-0759,0,0,95,87,69,1,413,2,NaN,NaN,NaN,NaN,NaN
4,United Air Lines Inc.,2023,2,4,26,3,2023-04-26,19977,N826UA,1784,14747,30559,SEA,"Seattle, WA",11292,30325,DEN,"Denver, CO",Morning,1,1116,1113,-3,0,0,1100-1159,1459,1453,-6,0,0,1400-1459,0,0,163,160,129,1,1024,5,NaN,NaN,NaN,NaN,NaN

In [122]:
### Removing original departure time block column

df.drop(['Dep_Time_Block'], axis = 1, inplace = True)

#### **Arr_Time_Block**

In [123]:
### Iterating over time block values in each row of the DF and simultaneously grouping and encoding them

time_blk = []
for blk in df['Arr_Time_Block']:
    if blk in early_morning:
      time_blk.append(0)
    elif blk in morning:
      time_blk.append(1)
    elif blk in early_afternoon:
      time_blk.append(2)
    elif blk in afternoon:
      time_blk.append(3)
    elif blk in evening:
      time_blk.append(4)
    else:
      time_blk.append(5)

In [124]:
### Converting the list into an array

time_blk = np.array(time_blk)

In [125]:
### Inserting array into DF

df.insert(loc = 25, column = 'Encoded_Arr_Time_Block', value = time_blk)

In [126]:
### Creating a list of arrival time block group names

time_blk_name = []
for blk in df['Encoded_Arr_Time_Block']:
    if blk == 0:
      time_blk_name.append('Early Morning')
    elif blk == 1:
      time_blk_name.append('Morning')
    elif blk == 2:
      time_blk_name.append('Early Afternoonn')
    elif blk == 3:
      time_blk_name.append('Afternoon')
    elif blk == 4:
      time_blk_name.append('Evening')
    else:
      time_blk_name.append('Night')

In [127]:
### Inserting new "Arr_Time_Block_Group" column into DF

time_blk_name = np.array(time_blk_name)
df.insert(loc = 25, column = 'Arr_Time_Block_Group', value = time_blk_name)

In [128]:
### Removing original arrival time block column

df.drop(['Arr_Time_Block'], axis = 1, inplace = True)

## **Write to Sharable File**

### Compressing and Exporting CSV File

In [129]:
zip_options = dict(method='zip',archive_name='Flight_On_Time_Data.csv')  
df.to_csv('../Data_Science/Exports/df_export.zip', index=False, compression=zip_options)